/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as PoolsRouteImport } from './routes/pools'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as CoinAddressRouteImport } from './routes/coin.$address'
import { Route as PoolAddressRouteImport } from './routes/pool.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsRoute = PoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinAddressRoute = CoinAddressRouteImport.update({
  id: '/coin/$address',
  path: '/coin/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolAddressRoute = PoolAddressRouteImport.update({
  id: '/pool/$address',
  path: '/pool/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/swap': typeof SwapRoute
  '/coin/$address': typeof CoinAddressRoute
  '/pool/$address': typeof PoolAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/swap': typeof SwapRoute
  '/coin/$address': typeof CoinAddressRoute
  '/pool/$address': typeof PoolAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/launch': typeof LaunchRoute
  '/pools': typeof PoolsRoute
  '/swap': typeof SwapRoute
  '/coin/$address': typeof CoinAddressRoute
  '/pool/$address': typeof PoolAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/launch'
    | '/pools'
    | '/swap'
    | '/coin/$address'
    | '/pool/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/launch'
    | '/pools'
    | '/swap'
    | '/coin/$address'
    | '/pool/$address'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/launch'
    | '/pools'
    | '/swap'
    | '/coin/$address'
    | '/pool/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LaunchRoute: typeof LaunchRoute
  PoolsRoute: typeof PoolsRoute
  SwapRoute: typeof SwapRoute
  CoinAddressRoute: typeof CoinAddressRoute
  PoolAddressRoute: typeof PoolAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools': {
      id: '/pools'
      path: '/pools'
      fullPath: '/pools'
      preLoaderRoute: typeof PoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$address': {
      id: '/coin/$address'
      path: '/coin/$address'
      fullPath: '/coin/$address'
      preLoaderRoute: typeof CoinAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool/$address': {
      id: '/pool/$address'
      path: '/pool/$address'
      fullPath: '/pool/$address'
      preLoaderRoute: typeof PoolAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LaunchRoute: LaunchRoute,
  PoolsRoute: PoolsRoute,
  SwapRoute: SwapRoute,
  CoinAddressRoute: CoinAddressRoute,
  PoolAddressRoute: PoolAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
